### PR TITLE
Update net_utils.c

### PR DESCRIPTION
**Pull request by FitiRL**
Typing error SIOCGIFHWADDR HWIF swap IFHW

### CODE REVIEW

**Comment by wowczarek** [comment]
Good find, thanks, this was only recently introduced.  I am working on the transport code at the moment and should push this along with the next commits, otherwise I will merge this.

**Comment by FitiRL** [comment]
I found others (VERY little) compilation errors.... check them

Thanks!

**Comment by wowczarek** [comment]
Thanks, I saw that. I need to clean up the debug build anyway so I should pick up any other issues like this one.

**Comment by FitiRL** [comment]
I am working on hardware-timestamping functionality but i have found some problem with this branch. Ptpd-2.3.1 (master) works perfectly but when i try to run this branch as unicast master i get "Segmentation Fault" error. I think that the problem resides in this branch (signaling.c file) because it has been modified. 

I has been debugging the code and i get noticed that, at line 234 of this branch&file (https://github.com/wowczarek/ptpd/blob/wowczarek-2.3.2-libcck/src/signaling.c) i have transportAddress = NULL, and then, it produces a segmentation fault error when calls ptpAddrCompare() method. 

I know that you are still working on it, and i dont really know if this is the best place to report this problem, but i am working on it to my school project and i want to help you too. I didnt open a Pull Request because i dont know how to solve this problem. Sorry if this is not the correct place to ask. 

Thanks in advance!!

**Comment by wowczarek** [comment]
Thanks again - as you can see, the 2.3.2-libcck branch is a full rewrite of the transports, so changes were significant and the protocol code does not directly operate on addresses anymore, and uses generic pointers instead. This used to store IPv4 addresses simply as uint32_s, so things are different now. Will try to pinpoint this issue.

Regards,
Wojciech

**Comment by wowczarek** [comment]
Thanks again - as you can see, the 2.3.2-libcck branch is a full rewrite of the transports, so changes were significant and the protocol code does not directly operate on addresses anymore, and uses generic pointers instead. This used to store IPv4 addresses simply as uint32_s, so things are different now.

Before I make the next commit, you can fix the offending line to look like this:

```
if(!ptpAddrIsEmpty(nodeTable->protocolAddress) && !ptpAddrIsEmpty(transportAddress) &&
```


Regards,
Wojciech

**Comment by wowczarek** [comment]
Should be fine now with github source.

**Pull request closed without merging**
